/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collection */
        get: operations["list_collection_api_v1_collection_get"];
        put?: never;
        /** Add Collection Item */
        post: operations["add_collection_item_api_v1_collection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collection/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Collection Item */
        patch: operations["update_collection_item_api_v1_collection__item_id__patch"];
        trace?: never;
    };
    "/api/v1/fragrances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fragrances */
        get: operations["list_fragrances_api_v1_fragrances_get"];
        put?: never;
        /** Create Fragrance */
        post: operations["create_fragrance_api_v1_fragrances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fragrances/{fragrance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fragrance */
        get: operations["get_fragrance_api_v1_fragrances__fragrance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collection Insights */
        get: operations["collection_insights_api_v1_insights_collection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Deletion
         * @description Phase one: mark the account pending.
         *
         *     The caller deletes the provider identity next; the provider's signed
         *     webhook then drives the actual data removal.
         */
        post: operations["request_deletion_api_v1_me_deletion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/deletion/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Deletion
         * @description Roll back the pending mark when the provider deletion call failed.
         */
        post: operations["cancel_deletion_api_v1_me_deletion_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/api/v1/wear-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wear Logs */
        get: operations["list_wear_logs_api_v1_wear_logs_get"];
        put?: never;
        /** Add Wear Log */
        post: operations["add_wear_log_api_v1_wear_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccordResponse */
        AccordResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Weight */
            weight: number;
        };
        /** BrandResponse */
        BrandResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** CollectionInsightsResponse */
        CollectionInsightsResponse: {
            /** Accords */
            accords: components["schemas"]["WeightedSlice"][];
            /** Average Rating */
            average_rating: number | null;
            /** Custom Items */
            custom_items: number;
            /** Distinct Fragrances Worn */
            distinct_fragrances_worn: number;
            /** Most Worn */
            most_worn: components["schemas"]["MostWornEntry"][];
            /** Occasions */
            occasions: components["schemas"]["WeightedSlice"][];
            /** Owned Items */
            owned_items: number;
            /** Ownership Types */
            ownership_types: components["schemas"]["CountSlice"][];
            /** Priced Items */
            priced_items: number;
            /** Rated Items */
            rated_items: number;
            /** Retired Items */
            retired_items: number;
            /** Seasons */
            seasons: components["schemas"]["WeightedSlice"][];
            /** Total Items */
            total_items: number;
            /** Total Purchase Value */
            total_purchase_value: string | null;
            /** Total Wears */
            total_wears: number;
            /** Unclassified Items */
            unclassified_items: number;
            /** Wears Last 30 Days */
            wears_last_30_days: number;
            /** Wishlist Items */
            wishlist_items: number;
        };
        /** CollectionItemCreateRequest */
        CollectionItemCreateRequest: {
            /** Bottle Size Ml */
            bottle_size_ml?: number | string | null;
            /** Custom Longevity */
            custom_longevity?: number | string | null;
            /** Custom Projection */
            custom_projection?: ("intimate" | "moderate" | "strong") | null;
            /**
             * Fragrance Id
             * Format: uuid
             */
            fragrance_id: string;
            /**
             * Ownership Type
             * @enum {string}
             */
            ownership_type: "bottle" | "decant" | "sample";
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Remaining Ml */
            remaining_ml?: number | string | null;
            /**
             * Status
             * @default owned
             * @enum {string}
             */
            status: "owned" | "wishlist" | "finished" | "sold";
            /** User Rating */
            user_rating?: number | null;
        };
        /** CollectionItemResponse */
        CollectionItemResponse: {
            /** Bottle Size Ml */
            bottle_size_ml: number | null;
            /** Custom Longevity */
            custom_longevity: number | null;
            /** Custom Projection */
            custom_projection: ("intimate" | "moderate" | "strong") | null;
            fragrance: components["schemas"]["FragranceSummary"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ownership Type
             * @enum {string}
             */
            ownership_type: "bottle" | "decant" | "sample";
            /** Purchase Date */
            purchase_date: string | null;
            /** Purchase Price */
            purchase_price: string | null;
            /** Remaining Ml */
            remaining_ml: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "owned" | "wishlist" | "finished" | "sold";
            /** User Rating */
            user_rating: number | null;
        };
        /**
         * CollectionItemUpdateRequest
         * @description Partial update. Every field is optional; omitted fields are untouched.
         *
         *     `status` is how an item is retired: setting it to `finished` or `sold`
         *     preserves the wear history that a hard delete would destroy.
         */
        CollectionItemUpdateRequest: {
            /** Bottle Size Ml */
            bottle_size_ml?: number | string | null;
            /** Custom Longevity */
            custom_longevity?: number | string | null;
            /** Custom Projection */
            custom_projection?: ("intimate" | "moderate" | "strong") | null;
            /** Ownership Type */
            ownership_type?: ("bottle" | "decant" | "sample") | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Remaining Ml */
            remaining_ml?: number | string | null;
            /** Status */
            status?: ("owned" | "wishlist" | "finished" | "sold") | null;
            /** User Rating */
            user_rating?: number | null;
        };
        /** CountSlice */
        CountSlice: {
            /** Count */
            count: number;
            /** Label */
            label: string;
        };
        /** DeletionResponse */
        DeletionResponse: {
            /**
             * Deletion Requested At
             * Format: date-time
             */
            deletion_requested_at: string;
            /**
             * Lifecycle State
             * @enum {string}
             */
            lifecycle_state: "active" | "deletion_pending";
        };
        /**
         * FragranceCreateRequest
         * @description A private custom fragrance.
         *
         *     Brand, name and concentration are required; the descriptive and
         *     classification metadata a curated entry carries is optional here, and
         *     insights report what is missing rather than guessing.
         */
        FragranceCreateRequest: {
            /** Brand Name */
            brand_name: string;
            /** Concentration */
            concentration: string;
            /** Description */
            description?: string | null;
            /** Longevity Score */
            longevity_score?: number | null;
            /** Name */
            name: string;
            /** Projection Level */
            projection_level?: ("intimate" | "moderate" | "strong") | null;
            /** Release Year */
            release_year?: number | null;
        };
        /** FragranceDetail */
        FragranceDetail: {
            /** Accords */
            accords: components["schemas"]["AccordResponse"][];
            brand: components["schemas"]["BrandResponse"];
            /** Concentration */
            concentration: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Blob Path */
            image_blob_path: string | null;
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
            /** Longevity Score */
            longevity_score: number | null;
            /** Name */
            name: string;
            /** Notes */
            notes: components["schemas"]["NoteResponse"][];
            /** Occasions */
            occasions: components["schemas"]["OccasionResponse"][];
            /** Projection Level */
            projection_level: ("intimate" | "moderate" | "strong") | null;
            /** Release Year */
            release_year: number | null;
            /** Seasons */
            seasons: components["schemas"]["SeasonResponse"][];
        };
        /** FragranceSummary */
        FragranceSummary: {
            brand: components["schemas"]["BrandResponse"];
            /** Concentration */
            concentration: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Blob Path */
            image_blob_path: string | null;
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
            /** Longevity Score */
            longevity_score: number | null;
            /** Name */
            name: string;
            /** Projection Level */
            projection_level: ("intimate" | "moderate" | "strong") | null;
            /** Release Year */
            release_year: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /**
             * Lifecycle State
             * @enum {string}
             */
            lifecycle_state: "active" | "deletion_pending";
            preferences: components["schemas"]["PreferencesResponse"];
        };
        /**
         * MeUpdateRequest
         * @description Only the display name is writable; email is owned by the provider.
         */
        MeUpdateRequest: {
            /** Display Name */
            display_name: string;
        };
        /** MostWornEntry */
        MostWornEntry: {
            /** Brand Name */
            brand_name: string;
            /**
             * Collection Item Id
             * Format: uuid
             */
            collection_item_id: string;
            /**
             * Fragrance Id
             * Format: uuid
             */
            fragrance_id: string;
            /** Fragrance Name */
            fragrance_name: string;
            /** Wear Count */
            wear_count: number;
        };
        /** NoteResponse */
        NoteResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "top" | "middle" | "base";
        };
        /** OccasionResponse */
        OccasionResponse: {
            /**
             * Occasion
             * @enum {string}
             */
            occasion: "work" | "casual" | "date" | "dinner" | "party" | "formal" | "gym" | "travel" | "other";
            /** Weight */
            weight: number;
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            /** Location */
            location?: string | null;
            /** Maximum Sprays */
            maximum_sprays?: number | null;
            /** Preferred Longevity */
            preferred_longevity?: number | null;
            /** Preferred Occasion */
            preferred_occasion?: ("work" | "casual" | "date" | "dinner" | "party" | "formal" | "gym" | "travel" | "other") | null;
            /** Preferred Projection */
            preferred_projection?: ("intimate" | "moderate" | "strong") | null;
            /** Preferred Season */
            preferred_season?: ("spring" | "summer" | "fall" | "winter") | null;
        };
        /**
         * PreferencesUpdateRequest
         * @description A full replacement of the preference set; omitted fields clear.
         */
        PreferencesUpdateRequest: {
            /** Location */
            location?: string | null;
            /** Maximum Sprays */
            maximum_sprays?: number | null;
            /** Preferred Longevity */
            preferred_longevity?: number | null;
            /** Preferred Occasion */
            preferred_occasion?: ("work" | "casual" | "date" | "dinner" | "party" | "formal" | "gym" | "travel" | "other") | null;
            /** Preferred Projection */
            preferred_projection?: ("intimate" | "moderate" | "strong") | null;
            /** Preferred Season */
            preferred_season?: ("spring" | "summer" | "fall" | "winter") | null;
        };
        /** SeasonResponse */
        SeasonResponse: {
            /**
             * Season
             * @enum {string}
             */
            season: "spring" | "summer" | "fall" | "winter";
            /** Weight */
            weight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WearLogCreateRequest */
        WearLogCreateRequest: {
            /**
             * Collection Item Id
             * Format: uuid
             */
            collection_item_id: string;
            /** Notes */
            notes?: string | null;
            /** Occasion */
            occasion?: ("work" | "casual" | "date" | "dinner" | "party" | "formal" | "gym" | "travel" | "other") | null;
            /** Setting */
            setting?: string | null;
            /** Sprays */
            sprays?: number | null;
            /**
             * Worn At
             * Format: date-time
             */
            worn_at: string;
        };
        /** WearLogResponse */
        WearLogResponse: {
            /** Brand Name */
            brand_name: string;
            /**
             * Collection Item Id
             * Format: uuid
             */
            collection_item_id: string;
            /**
             * Fragrance Id
             * Format: uuid
             */
            fragrance_id: string;
            /** Fragrance Name */
            fragrance_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes?: string | null;
            /** Occasion */
            occasion?: ("work" | "casual" | "date" | "dinner" | "party" | "formal" | "gym" | "travel" | "other") | null;
            /** Setting */
            setting?: string | null;
            /** Sprays */
            sprays?: number | null;
            /**
             * Worn At
             * Format: date-time
             */
            worn_at: string;
        };
        /** WeightedSlice */
        WeightedSlice: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Share */
            share: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_collection_api_v1_collection_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_collection_item_api_v1_collection_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionItemCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_collection_item_api_v1_collection__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionItemUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fragrances_api_v1_fragrances_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragranceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fragrance_api_v1_fragrances_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FragranceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragranceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fragrance_api_v1_fragrances__fragrance_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                fragrance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragranceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collection_insights_api_v1_insights_collection_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionInsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_deletion_api_v1_me_deletion_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_deletion_api_v1_me_deletion_cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wear_logs_api_v1_wear_logs_get: {
        parameters: {
            query?: {
                collection_item_id?: string | null;
                fragrance_id?: string | null;
                worn_from?: string | null;
                worn_to?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WearLogResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_wear_log_api_v1_wear_logs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WearLogCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WearLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
