from scentiq_api.schemas.calendar import (
    AuthorizationResponse,
    CalendarConnectionResponse,
    CalendarEventResponse,
    CalendarEventUpdateRequest,
    CalendarProviderStatus,
    CalendarSourceResponse,
    CalendarSourceUpdateRequest,
    OAuthCallbackRequest,
)
from scentiq_api.schemas.catalog import (
    AccordResponse,
    BrandResponse,
    CommunityResponse,
    FragranceCreateRequest,
    FragranceDetail,
    FragranceSummary,
    NoteResponse,
    OccasionResponse,
    PerfumerResponse,
    SeasonResponse,
    SourceResponse,
)
from scentiq_api.schemas.collection import (
    CollectionItemCreateRequest,
    CollectionItemResponse,
    CollectionItemUpdateRequest,
)
from scentiq_api.schemas.discovery import DiscoveryResult
from scentiq_api.schemas.enums import (
    RETIRED_STATUSES,
    CollectionStatus,
    LifecycleState,
    NoteStage,
    Occasion,
    OwnershipType,
    Projection,
    Season,
    TemperatureUnit,
)
from scentiq_api.schemas.identity import (
    DeletionResponse,
    MeResponse,
    MeUpdateRequest,
    PreferencesResponse,
    PreferencesUpdateRequest,
)
from scentiq_api.schemas.insights import (
    CollectionInsightsResponse,
    CountSlice,
    MostWornEntry,
    WeightedSlice,
)
from scentiq_api.schemas.layering import LayeringMode, LayeringSuggestion
from scentiq_api.schemas.pages import (
    DashboardPageResponse,
    FragrancePageResponse,
    LayeringPageResponse,
    WeekFragrance,
    WeekPageResponse,
)
from scentiq_api.schemas.recommendations import (
    RecommendationBundleResponse,
    RecommendationPayload,
)
from scentiq_api.schemas.wear import WearLogCreateRequest, WearLogResponse
from scentiq_api.schemas.weather import ForecastDay, PlaceResponse, WeatherForecastResponse

__all__ = [
    "RETIRED_STATUSES",
    "AccordResponse",
    "AuthorizationResponse",
    "BrandResponse",
    "CalendarConnectionResponse",
    "CalendarEventResponse",
    "CalendarEventUpdateRequest",
    "CalendarProviderStatus",
    "CalendarSourceResponse",
    "CalendarSourceUpdateRequest",
    "CollectionInsightsResponse",
    "CollectionItemCreateRequest",
    "CollectionItemResponse",
    "CollectionItemUpdateRequest",
    "CollectionStatus",
    "CommunityResponse",
    "CountSlice",
    "DashboardPageResponse",
    "DeletionResponse",
    "DiscoveryResult",
    "ForecastDay",
    "FragranceCreateRequest",
    "FragranceDetail",
    "FragrancePageResponse",
    "FragranceSummary",
    "LayeringMode",
    "LayeringPageResponse",
    "LayeringSuggestion",
    "LifecycleState",
    "MeResponse",
    "MeUpdateRequest",
    "MostWornEntry",
    "NoteResponse",
    "NoteStage",
    "OAuthCallbackRequest",
    "Occasion",
    "OccasionResponse",
    "OwnershipType",
    "PerfumerResponse",
    "PlaceResponse",
    "PreferencesResponse",
    "PreferencesUpdateRequest",
    "Projection",
    "RecommendationBundleResponse",
    "RecommendationPayload",
    "Season",
    "SeasonResponse",
    "SourceResponse",
    "TemperatureUnit",
    "WearLogCreateRequest",
    "WearLogResponse",
    "WeatherForecastResponse",
    "WeekFragrance",
    "WeekPageResponse",
    "WeightedSlice",
]
