using '../main.bicep'

param location = 'eastus'
param postgresLocation = 'northcentralus'
param environmentName = 'dev'
param useExistingFoundation = true
param workspaceName = 'scentiq-law-dev-us'
param storageName = 'scentiqstrgdevus'
param keyVaultName = 'scentiq-kv-dev-eus'
param postgresServerName = 'scentiq-pg-dev-eus'
param identityName = 'scentiq-api-id-dev-eus'
param containerEnvironmentName = 'scentiq-cae-dev-eus'
param registryName = 'scentiqacrdevus'
param applicationInsightsName = 'scentiq-appi-dev-eus'
param apiAppName = 'scentiq-api-dev-eus'
param webAppName = 'scentiq-web-dev-eus'
param migrationJobName = 'scentiq-migrate-dev-eus'
param apiImage = 'scentiqacrdevus.azurecr.io/scentiq-api@sha256:63804207a705c4140ea2be122fc846a05a264beac35be55f29eac23f7d33ff7b'
param webImage = 'scentiqacrdevus.azurecr.io/scentiq-web@sha256:cd2bcadef061c1b9bf3933623a9de3aefd0b88868f1f6be09808296895ebb3d7'
