"""add fragrance domain

Revision ID: 68bfbd3cf8fb
Revises: 20260808_0001
Create Date: 2026-08-09 04:53:53.541703

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "68bfbd3cf8fb"
down_revision: str | Sequence[str] | None = "20260808_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accords",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accords")),
        sa.UniqueConstraint("name", name=op.f("uq_accords_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_accords_slug")),
    )
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("name", name=op.f("uq_brands_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_brands_slug")),
    )
    op.create_table(
        "notes",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
        sa.UniqueConstraint("name", name=op.f("uq_notes_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_notes_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "calendar_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("setting", sa.String(length=40), nullable=True),
        sa.Column("formality", sa.String(length=20), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_calendar_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
        sa.UniqueConstraint(
            "user_id", "external_reference", name="calendar_user_external_reference"
        ),
    )
    op.create_index(
        op.f("ix_calendar_events_starts_at"), "calendar_events", ["starts_at"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_user_id"), "calendar_events", ["user_id"], unique=False
    )
    op.create_table(
        "fragrances",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("concentration", sa.String(length=40), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_blob_path", sa.String(length=512), nullable=True),
        sa.Column("longevity_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("projection_level", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "projection_level IS NULL OR projection_level IN ('intimate', 'moderate', 'strong')",
            name=op.f("ck_fragrances_projection_level_value"),
        ),
        sa.CheckConstraint(
            "longevity_score IS NULL OR longevity_score BETWEEN 0 AND 10",
            name=op.f("ck_fragrances_longevity_score_range"),
        ),
        sa.CheckConstraint(
            "release_year IS NULL OR release_year BETWEEN 1700 AND 2100",
            name=op.f("ck_fragrances_release_year_range"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_fragrances_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fragrances")),
        sa.UniqueConstraint("brand_id", "name", "concentration", name="fragrance_identity"),
    )
    op.create_index(op.f("ix_fragrances_brand_id"), "fragrances", ["brand_id"], unique=False)
    op.create_index(op.f("ix_fragrances_name"), "fragrances", ["name"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_season", sa.String(length=10), nullable=True),
        sa.Column("preferred_occasion", sa.String(length=20), nullable=True),
        sa.Column("preferred_projection", sa.String(length=20), nullable=True),
        sa.Column("preferred_longevity", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("maximum_sprays", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "preferred_projection IS NULL OR preferred_projection IN "
            "('intimate', 'moderate', 'strong')",
            name=op.f("ck_user_preferences_preferred_projection_value"),
        ),
        sa.CheckConstraint(
            "preferred_season IS NULL OR preferred_season IN "
            "('spring', 'summer', 'fall', 'winter')",
            name=op.f("ck_user_preferences_preferred_season_value"),
        ),
        sa.CheckConstraint(
            "maximum_sprays IS NULL OR maximum_sprays BETWEEN 1 AND 20",
            name=op.f("ck_user_preferences_maximum_sprays_range"),
        ),
        sa.CheckConstraint(
            "preferred_longevity IS NULL OR preferred_longevity BETWEEN 0 AND 10",
            name=op.f("ck_user_preferences_preferred_longevity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "weather_snapshots",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("location_label", sa.String(length=160), nullable=False),
        sa.Column("forecast_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_celsius", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("humidity", sa.Integer(), nullable=True),
        sa.Column("precipitation_probability", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("condition", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "humidity IS NULL OR humidity BETWEEN 0 AND 100",
            name=op.f("ck_weather_snapshots_humidity_range"),
        ),
        sa.CheckConstraint(
            "precipitation_probability IS NULL OR precipitation_probability BETWEEN 0 AND 1",
            name=op.f("ck_weather_snapshots_precipitation_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_weather_snapshots_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_snapshots")),
    )
    op.create_index(
        op.f("ix_weather_snapshots_forecast_at"), "weather_snapshots", ["forecast_at"], unique=False
    )
    op.create_index(
        op.f("ix_weather_snapshots_user_id"), "weather_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "fragrance_accords",
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("accord_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.CheckConstraint(
            "weight BETWEEN 0 AND 1", name=op.f("ck_fragrance_accords_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["accord_id"], ["accords.id"], name=op.f("fk_fragrance_accords_accord_id_accords")
        ),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_fragrance_accords_fragrance_id_fragrances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("fragrance_id", "accord_id", name=op.f("pk_fragrance_accords")),
    )
    op.create_table(
        "fragrance_notes",
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=10), nullable=False),
        sa.CheckConstraint(
            "stage IN ('top', 'middle', 'base')", name=op.f("ck_fragrance_notes_stage_value")
        ),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_fragrance_notes_fragrance_id_fragrances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["notes.id"], name=op.f("fk_fragrance_notes_note_id_notes")
        ),
        sa.PrimaryKeyConstraint(
            "fragrance_id", "note_id", "stage", name=op.f("pk_fragrance_notes")
        ),
    )
    op.create_table(
        "fragrance_occasions",
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("occasion", sa.String(length=10), nullable=False),
        sa.Column("weight", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.CheckConstraint(
            "occasion IN ('work', 'casual', 'date', 'dinner', 'party', "
            "'formal', 'gym', 'travel', 'other')",
            name=op.f("ck_fragrance_occasions_occasion_value"),
        ),
        sa.CheckConstraint(
            "weight BETWEEN 0 AND 1", name=op.f("ck_fragrance_occasions_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_fragrance_occasions_fragrance_id_fragrances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("fragrance_id", "occasion", name=op.f("pk_fragrance_occasions")),
    )
    op.create_table(
        "fragrance_seasons",
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("season", sa.String(length=10), nullable=False),
        sa.Column("weight", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.CheckConstraint(
            "season IN ('spring', 'summer', 'fall', 'winter')",
            name=op.f("ck_fragrance_seasons_season_value"),
        ),
        sa.CheckConstraint(
            "weight BETWEEN 0 AND 1", name=op.f("ck_fragrance_seasons_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_fragrance_seasons_fragrance_id_fragrances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("fragrance_id", "season", name=op.f("pk_fragrance_seasons")),
    )
    op.create_table(
        "layering_logs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("primary_fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("secondary_fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("worn_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "primary_fragrance_id <> secondary_fragrance_id",
            name=op.f("ck_layering_logs_distinct_fragrances"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name=op.f("ck_layering_logs_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["primary_fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_layering_logs_primary_fragrance_id_fragrances"),
        ),
        sa.ForeignKeyConstraint(
            ["secondary_fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_layering_logs_secondary_fragrance_id_fragrances"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_layering_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layering_logs")),
    )
    op.create_index(op.f("ix_layering_logs_user_id"), "layering_logs", ["user_id"], unique=False)
    op.create_index(op.f("ix_layering_logs_worn_at"), "layering_logs", ["worn_at"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recommended_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", sa.String(length=40), nullable=False),
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("recommended_sprays", sa.Integer(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recommended_sprays BETWEEN 1 AND 30",
            name=op.f("ck_recommendations_recommended_sprays_range"),
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name=op.f("ck_recommendations_score_range")),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_recommendations_fragrance_id_fragrances"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_recommendations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(
        op.f("ix_recommendations_recommended_for"),
        "recommendations",
        ["recommended_for"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False
    )
    op.create_table(
        "user_collection",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("ownership_type", sa.String(length=10), nullable=False),
        sa.Column("bottle_size_ml", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("remaining_ml", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("custom_longevity", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("custom_projection", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "custom_projection IS NULL OR custom_projection IN ('intimate', 'moderate', 'strong')",
            name=op.f("ck_user_collection_custom_projection_value"),
        ),
        sa.CheckConstraint(
            "ownership_type IN ('bottle', 'decant', 'sample')",
            name=op.f("ck_user_collection_ownership_type_value"),
        ),
        sa.CheckConstraint(
            "status IN ('owned', 'wishlist', 'finished', 'sold')",
            name=op.f("ck_user_collection_status_value"),
        ),
        sa.CheckConstraint(
            "bottle_size_ml IS NULL OR bottle_size_ml > 0",
            name=op.f("ck_user_collection_bottle_size_positive"),
        ),
        sa.CheckConstraint(
            "custom_longevity IS NULL OR custom_longevity BETWEEN 0 AND 10",
            name=op.f("ck_user_collection_custom_longevity_range"),
        ),
        sa.CheckConstraint(
            "purchase_price IS NULL OR purchase_price >= 0",
            name=op.f("ck_user_collection_purchase_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "remaining_ml IS NULL OR remaining_ml >= 0",
            name=op.f("ck_user_collection_remaining_nonnegative"),
        ),
        sa.CheckConstraint(
            "user_rating IS NULL OR user_rating BETWEEN 1 AND 5",
            name=op.f("ck_user_collection_rating_range"),
        ),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_user_collection_fragrance_id_fragrances"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_collection_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_collection")),
    )
    op.create_index(
        op.f("ix_user_collection_fragrance_id"), "user_collection", ["fragrance_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_collection_user_id"), "user_collection", ["user_id"], unique=False
    )
    op.create_table(
        "wishlists",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_wishlists_priority_range")),
        sa.ForeignKeyConstraint(
            ["fragrance_id"], ["fragrances.id"], name=op.f("fk_wishlists_fragrance_id_fragrances")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_wishlists_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wishlists")),
        sa.UniqueConstraint("user_id", "fragrance_id", name="wishlist_user_fragrance"),
    )
    op.create_table(
        "recommendation_candidates",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("fragrance_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("score_components", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("rank > 0", name=op.f("ck_recommendation_candidates_rank_positive")),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100", name=op.f("ck_recommendation_candidates_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["fragrance_id"],
            ["fragrances.id"],
            name=op.f("fk_recommendation_candidates_fragrance_id_fragrances"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_recommendation_candidates_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_candidates")),
        sa.UniqueConstraint(
            "recommendation_id", "fragrance_id", name="recommendation_candidate_fragrance"
        ),
        sa.UniqueConstraint("recommendation_id", "rank", name="recommendation_candidate_rank"),
    )
    op.create_index(
        op.f("ix_recommendation_candidates_recommendation_id"),
        "recommendation_candidates",
        ["recommendation_id"],
        unique=False,
    )
    op.create_table(
        "wear_logs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("collection_item_id", sa.Uuid(), nullable=False),
        sa.Column("worn_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sprays", sa.Integer(), nullable=True),
        sa.Column("occasion", sa.String(length=20), nullable=True),
        sa.Column("setting", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "sprays IS NULL OR sprays BETWEEN 1 AND 30", name=op.f("ck_wear_logs_sprays_range")
        ),
        sa.ForeignKeyConstraint(
            ["collection_item_id"],
            ["user_collection.id"],
            name=op.f("fk_wear_logs_collection_item_id_user_collection"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_wear_logs_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wear_logs")),
    )
    op.create_index(op.f("ix_wear_logs_user_id"), "wear_logs", ["user_id"], unique=False)
    op.create_index(op.f("ix_wear_logs_worn_at"), "wear_logs", ["worn_at"], unique=False)
    op.create_table(
        "wear_feedback",
        sa.Column("wear_log_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("longevity", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("projection", sa.String(length=20), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "projection IS NULL OR projection IN ('intimate', 'moderate', 'strong')",
            name=op.f("ck_wear_feedback_projection_value"),
        ),
        sa.CheckConstraint(
            "longevity IS NULL OR longevity BETWEEN 0 AND 10",
            name=op.f("ck_wear_feedback_longevity_range"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name=op.f("ck_wear_feedback_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wear_feedback_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["wear_log_id"], ["wear_logs.id"], name=op.f("fk_wear_feedback_wear_log_id_wear_logs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wear_feedback")),
        sa.UniqueConstraint("wear_log_id", name=op.f("uq_wear_feedback_wear_log_id")),
    )
    op.create_index(op.f("ix_wear_feedback_user_id"), "wear_feedback", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wear_feedback_user_id"), table_name="wear_feedback")
    op.drop_table("wear_feedback")
    op.drop_index(op.f("ix_wear_logs_worn_at"), table_name="wear_logs")
    op.drop_index(op.f("ix_wear_logs_user_id"), table_name="wear_logs")
    op.drop_table("wear_logs")
    op.drop_index(
        op.f("ix_recommendation_candidates_recommendation_id"),
        table_name="recommendation_candidates",
    )
    op.drop_table("recommendation_candidates")
    op.drop_table("wishlists")
    op.drop_index(op.f("ix_user_collection_user_id"), table_name="user_collection")
    op.drop_index(op.f("ix_user_collection_fragrance_id"), table_name="user_collection")
    op.drop_table("user_collection")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_recommended_for"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_layering_logs_worn_at"), table_name="layering_logs")
    op.drop_index(op.f("ix_layering_logs_user_id"), table_name="layering_logs")
    op.drop_table("layering_logs")
    op.drop_table("fragrance_seasons")
    op.drop_table("fragrance_occasions")
    op.drop_table("fragrance_notes")
    op.drop_table("fragrance_accords")
    op.drop_index(op.f("ix_weather_snapshots_user_id"), table_name="weather_snapshots")
    op.drop_index(op.f("ix_weather_snapshots_forecast_at"), table_name="weather_snapshots")
    op.drop_table("weather_snapshots")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_fragrances_name"), table_name="fragrances")
    op.drop_index(op.f("ix_fragrances_brand_id"), table_name="fragrances")
    op.drop_table("fragrances")
    op.drop_index(op.f("ix_calendar_events_user_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_starts_at"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_table("users")
    op.drop_table("notes")
    op.drop_table("brands")
    op.drop_table("accords")
    # ### end Alembic commands ###
