"use client";

import { Bell, CalendarDays, Lock, MapPin, SlidersHorizontal, UserRound } from "lucide-react";

import { ApiStatus } from "@/components/api-status";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { demoUser } from "@/lib/demo";

export function SettingsExperience() {
  return <section className="page"><PageHeader eyebrow="Make it yours" title="Settings" description="Frontend-only controls that preview future preference and connection surfaces." /><p className="demo-disclosure"><Badge>Demo controls</Badge> Changes are not persisted and no accounts or calendar connections are created.</p><div className="settings-grid"><SettingsCard icon={UserRound} title="Profile"><Field label="Display name"><Input defaultValue={demoUser.name} /></Field><Field label="Email"><Input value="maya@example.demo" readOnly /></Field></SettingsCard><SettingsCard icon={MapPin} title="Location"><Field label="Recommendation location"><Input defaultValue={demoUser.location} /></Field><label className="toggle-row"><span><strong>Use location for weather</strong><small>Provider connection arrives in a later phase.</small></span><input type="checkbox" defaultChecked /></label></SettingsCard><SettingsCard icon={SlidersHorizontal} title="Recommendation preferences"><Field label="Projection preference"><select className="select" defaultValue="Moderate"><option>Intimate</option><option>Moderate</option><option>Strong</option></select></Field><Field label="Longevity preference"><select className="select" defaultValue="7+ hours"><option>Any</option><option>5+ hours</option><option>7+ hours</option><option>10+ hours</option></select></Field><Field label="Maximum sprays"><Input type="number" defaultValue={5} min={1} max={12} /></Field></SettingsCard><SettingsCard icon={CalendarDays} title="Calendar connections"><p>Calendar integrations are intentionally unavailable in this demo.</p><button className="connection-row" disabled><span>Google Calendar</span><Badge>Coming later</Badge></button><button className="connection-row" disabled><span>Outlook Calendar</span><Badge>Coming later</Badge></button></SettingsCard><SettingsCard icon={Bell} title="Notifications"><label className="toggle-row"><span><strong>Morning recommendation</strong><small>Preview only</small></span><input type="checkbox" defaultChecked /></label><label className="toggle-row"><span><strong>Weekly planning reminder</strong><small>Preview only</small></span><input type="checkbox" /></label></SettingsCard><SettingsCard icon={Lock} title="Privacy"><p>Your demo interactions stay in browser memory for the current session. Authentication and production privacy controls are out of scope for this shell.</p></SettingsCard><Card className="settings-system"><CardContent><p className="eyebrow">System</p><h2>API availability</h2><ApiStatus /><p className="muted">Same-origin foundation health status. Product screens use typed demo data in this phase.</p></CardContent></Card></div></section>;
}

function SettingsCard({ icon: Icon, title, children }: { icon: typeof UserRound; title: string; children: React.ReactNode }) { return <Card><CardContent><div className="settings-title"><Icon size={19} /><h2>{title}</h2></div><div className="stack">{children}</div></CardContent></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="label">{label}</span>{children}</label>; }
